name: Build and Publish Electron Package

on:
  push:
    branches:
      - production

jobs:
  build:
    name: Build and Publish Electron Package
    runs-on: windows-latest
    needs: bump-version
    env:
      NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
      - name: Bump Version
        run: npm version patch
      - name: Build Package
        run: npm install
        env:
          NODE_ENV: dev
      - run: npm run build
      - run: npm run publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}