name: Build and Publish Electron Package

on:
  push:
    branches:
      - production

jobs:
  build:
    name: Build and Publish Electron Package
    runs-on: windows-latest
    env:
      NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
      - name: Bump Version
        run: npm --no-git-tag-version version patch
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: commit
        run: |
          git add package.json package-lock.json
          git commit -m "Bump version code"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'production'
      - name: Build Package
        run: npm install
        env:
          NODE_ENV: dev
      - run: npm run build
      - run: npm run publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pull-request:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Pulling ${{ github.ref }} into master"