name: Build and Publish Electron Package

on:
  push:
    branches:
      - production

jobs:
  build:
    name: Build and Publish Electron Package
    runs-on: windows-latest
    env:
      NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
      - name: Automated Version Bump
        uses: RalphSleigh/gh-action-bump-version@master
      - name: Build Package
        run: npm install
        env:
          NODE_ENV: dev
      - run: npm run build
      - run: npm run publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update version code
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: 'Update version code'
          body: |
            Update version code
          branch: master