name: Build and Publish Electron Package

on:
  push:
    branches:
      - production

jobs:
  build:
    name: Build and Publish Electron Package
    runs-on: windows-latest
    env:
      NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
      - name: Bump Version
        run: npm --no-git-tag-version version patch
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: commit
        run: |
          git add package.json package-lock.json
          git commit -m "Bump version code"
        env:
          GIT_TRACE: 1
          GIT_CURL_VERBOSE: 1
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'production'
#      - name: Automated Version Bump
#        uses: RalphSleigh/gh-action-bump-version@master
#      - name: Build Package
#        run: npm install
#        env:
#          NODE_ENV: dev
#      - run: npm run build
#      - run: npm run publish
#        env:
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Open RP
          uses: technote-space/create-pr-action@v2
          with:
            PR_BRANCH_NAME: 'update_version'
            PR_TITLE: 'Update version'